services:
  client:
    build:
      context: ./roster-service/client
      dockerfile: Dockerfile
    container_name: roster-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_TAC_OP_API_URL=http://localhost:8000
    depends_on:
      - server
      - tactical-optimization
    networks:
      - roster-network

  server:
    build:
      context: ./roster-service/server
      dockerfile: Dockerfile
    container_name: roster-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./roster-service/server:/app
      - ./roster-service/server/instance:/app/instance
    networks:
      - roster-network

  tactical-optimization:
    build:
      context: ./tactical-optimization-service/src
      dockerfile: Dockerfile
    container_name: tactical-optimization
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - ROSTER_SERVICE_URL=http://server:5000
    volumes:
      - ./tactical-optimization-service/src:/app
    depends_on:
      - server
    networks:
      - roster-network

  broker:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Listen on all interfaces inside the container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Tell clients to connect to broker:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - roster-network
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:

networks:
  roster-network:
    driver: bridge
